### ISSUE TITLE
Fix `dupIO` for CAFs

### ISSUE THREAD

**Issue by edsko** [well-typed/dupIO#9]
See #4 for reproducer.

**Comment by edsko** [comment]
Duplicating the comment on the PR here: after changing ALLOC_PRIM to ALLOC_PRIM_P, these tests now pass, but only if not using the debug RTS. I've enabled the debug RTS by default in this branch to make this clearer.

**Comment by AndreasPK** [comment]
Matt pointed me to this. If I understand correctly you have some code passing in the non-debug RTS which segfaults in the debug RTS?

Would it be easy for you to distill this down into one haskell and one cmm file? That would make it (even) easier to look into this.

**Comment by edsko** [comment]
@AndreasPK Ok, I can give you that.

**Comment by edsko** [comment]
@AndreasPK Ok, see https://github.com/well-typed/dupIO/pull/4/commits/c67db693cccd29c133ca0a5b7b67780d456eba49 for a standalone reproducer, consisting of a single `.hs` and a single `.cmm` file. The `.cmm` file is the same as the one in the library, except that it omits a call to a C function to issue a warning if particular type of closure cannot be duplicated (to avoid the need for the external `.c` file. The `.hs` file truly is barebones; I did not manage to simplify it any further without the segfault disappearing.

For convenience there is also a `Makefile` that builds (and runs) both with and without the debug RTS; only the version with the debug RTS segfaults.

**Comment by bgamari** [comment]
I have looked at the CAF situation. Unfortunately it is quite grim.

In short, much of the complexity stems from the fact that in a CAF's entry code, the RHS of the CAF is inextricably tangled with various bookkeeping logic injected by the code generator. Specifically, the entry code calls the RTS's `newCAF` function, which does the following:

 * Lock the CAF to ensure mutual exclusion with other threads
 * Allocate a blackhole in the dynamic heap which will ultimately point to the evaluation result
 * Update the CAF to be `IND_STATIC` pointing to that blackhole
 * If `-keep-cafs` is enabled: Add the CAF onto the RTS's `dyn_caf_list`
 * In the `DEBUG` RTS: Add the CAF onto the RTS's `debug_caf_list`
 * Push the CAF to the mutable list

There are a few things problematic about this. First, we need to duplicate the CAF itself (ideally once per entry, to maintain the expected semantics of `dup`) so that `newCAF` has something to work on. This naturally brings with it the challenges of object lifetime. One might think that we could possibly delegate lifetime issues to the GC by allocating the duplicate CAF in the dynamic heap and allowing the GC to collect it when it becomes unreachable (which would be essentially immediately). Sadly, things aren't this simple since the CAF is pushed to the mutable and various CAF lists; we would somehow need to ensure that the duplicate CAF was removed from these lists before the it is freed.

Sadly, fixing this is not easy. I give a few alternatives below.

# Separating CAF RHS from book-keeping logic
Ultimately this problem would be side-stepped if we had a way of entering the CAF's RHS without running the usual CAF prologue (`newCAF`). One way of accomplishing this would be to, at compilation time, factor the CAF's RHS into a new, non-updateable binding. That is, rewrite
```haskell
caf = <rhs>
```
into something like
```haskell
caf  = caf_body ()

caf_body = \(s :: ()) -> <rhs>
```
This transformation could be done with either a Core-to-Core plugin (at the end of the pipeline) or, better, an STG plugin (although sadly we [don't yet have](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/8349) such things).

If we could then retrieve the info table of `caf_body` from that of `caf` we could teach `dup` to enter `caf_body` instead of `caf`. Sadly', it's not immediately clear how to build such a mapping with the plugin tools we have today.

# Weakening `dup` semantics for CAFs

Another option here would be to provide a weaker semantics for CAFs. For instance, we could teach `dup` to simply revert the CAF after evaluation has finished. This would provide a weaker guarantee that the result of `x = dup caf` would only have a unique referent if there were no other entries while evaluation is underway. 
I am not certain how useful these weaker semantics are, however.

Operationally, this would be accomplished by pushing a stack frame which will revert the CAF when entering `dup`. Specifically, `dupClosure` would look something like:
```c
dupClosure(P_ clos) {
    W_ info, type;
    clos = UNTAG(R1);
    info = %INFO_PTR(clos);
    type = TO_W_(%INFO_TYPE(%STD_INFO(info)));

    // Check if we can/should copy this closure
    switch [0 .. N_CLOSURE_TYPES] type {
      case THUNK_STATIC:
        Sp_adj(-3);
        Sp(2) = StgHeader_info(clos);
        Sp(1) = clos;
        Sp(0) = dup_revert_caf_info;
        ENTER(clos);
      ...
}

// N.B. we don't rely on on StgIndStatic.saved_info as this may be clobbered by the RTS.
INFO_TABLE_RET(dup_revert_caf, RET_SMALL, W_ info_ptr, P_ caf, W_ orig_info)
    return (P_ ret)
{
     StgHeader_info(caf) = orig_info;
     StgIndStatic_indirectee(caf) = 0;
     return (ret);
}
```
However, doing this is a bit subtle since we need to ensure that any threads which block on the blackhole during evaluation are soundly woken up when evaluation finishes, despite the reversion. From a quick read of the associated logic, I think the status quo should be safe. Specifically, the entry code of `stg_IND_STATIC` (which is what the original CAF will become) will immediately enter its indirectee (which will be an `stg_CAF_BLACKHOLE`). From this point forth the original CAF should not be referenced by the second enter-er.

# In GHC: Separating the prologue
Currently the code generator emits the CAF prologue for every CAF binding. Perhaps it would be better if GHC had a more generic info table and entry code for CAFs (call it `stg_CAF_info`). The payload of the CAF closure would then consist of a pointer to a function closure which will compute its value:
```c
struct StgCAF {
  StgHeader header;
  StgClosure *rhs;
  StgWord padding[2]; // to ensure that an StgIndStatic fits in the same storage
}
```
The entry code of `stg_CAF_info` would then look as follows:
```haskell
INFO_TABLE(stg_CAF, 1,0,CAF, "CAF", "CAF")
    (P_ rhs)
{
    P_ bh;
    (bh) = ccall newCAF(BaseReg, R1);
    if (bh == 0) {
        ENTER(R1);
    } else {
        Sp_adj(-2)
        Sp(1) = bh;
        Sp(0) = stg_bh_upd_frame_info;
        ENTER(rhs);
    }
}
```
Note to self: perhaps `rhs` should be `R1`-relative, to avoid GOT entries in PIC code? Also, presumably `saved_info` should become `saved_rhs`, in which case maybe the `rhs` field should just be added to `StgIndStatic` and remain immutable. This would require that we do away with the intrusive `debug_caf_list`, which would probably be a good thing anyways.

This scheme would then make it much easier to implement `dup` as we could enter the RHS without bringing in the usual CAF logic.

On the other hand, it would incur more control flow on CAF entry. On the third hand, it would shrink the entry code of every CAF by a few dozen bytes, perhaps improving I$ utilization. On the fourth hand, CAF entry is generally an O(1) cost which will not contribute appreciably to runtime for a long-running program and consequently this likely won't make much of a difference either way.

# Overriding `newCAF`
One, quite hacky, option to side-step this issues above would be to use an `LD_PRELOAD` library to override `newCAF`. However, this is fairly platform-specific and use of `LD_PRELOAD` like this is generally frowned upon for security reasons.

**Comment by edsko** [comment]
After @bgamari 's thorough (and depressing :grimacing: ) analysis, @adamgundry and I discussed this, and we think that actually provided we duplicate _enough_, not duplicating CAFs is not a deal breaker. It just means that we might retain _some_ of the chain, but as long as we break links often enough, it's fine (documented this in #21). So @adamgundry 's work-around from #9 is sufficient. 

Thanks everyone!
